// TASK create a horoscope app where the user can enter their birthday and get a horoscope. There should be a minimum version of 12 unique horoscopes.

//create event listener to run user input
document.querySelector('#showMe').addEventListener('click', giveSign)

//create a function for the event listener to evaluate user's sign

function giveSign() {
	let month = document.querySelector('#month').value
	let date = document.querySelector('#date').value
	
	if (month == 03 && date >= 21 || month == 04 && date <= 19) {
		result = ('Aries')
		document.querySelector('#result').innerHTML = 'Aries'
		document.querySelector('#result').style.color = 'rgb(255,40,0)'
		document.querySelector('#p1').innerHTML = `Aries individuals exhibit distinct aspects of their personality when they are alone versus when they are with others. When alone, Aries values their independence, using this time for introspection, personal growth, and creative pursuits. They may also experience restlessness if they don't find engaging activities to occupy their solitary moments.`
		document.querySelector('#p2').innerHTML = `In social situations, Aries takes on a leadership role, showcasing their assertiveness and ability to inspire and lead others. They bring their energetic and enthusiastic nature to the group, often becoming the life of the party. Aries can also become more competitive, enjoying friendly challenges and engaging in activities where they can demonstrate their skills. Their loyalty and straightforward communication style shine when interacting with others, making them dependable and honest friends and companions.`
		document.querySelector('#p3').innerHTML = `One unique aspect of Aries personalities is their remarkable ability to bounce back from setbacks and failures. Aries individuals possess a strong and resilient spirit that allows them to quickly recover from disappointments and keep moving forward with undiminished enthusiasm. Their natural optimism and determination help them view challenges as opportunities for growth and learning rather than as obstacles. This resilience makes Aries individuals excellent at handling adversity and pursuing their goals with unwavering determination, even in the face of setbacks.`
		document.querySelector('#p4').innerHTML = `While Aries' competitive nature and desire for success drive them to push their limits, their ability to rise above failures distinguishes them as individuals who don't easily give up. They are willing to take risks and embrace new challenges, knowing that even if they stumble along the way, they have the inner strength and determination to persevere and ultimately succeed. This resilience is a defining and admirable trait of Aries personalities.`
		document.querySelector('#p5').innerHTML = '𓃶'
	} else if (month == 04 && date >= 20 || month == 05 && date <= 20) {
		result = ('Taurus')
		document.querySelector('#result').innerHTML = 'Taurus'
		document.querySelector('#p1').innerHTML = `Step into the world of Taurus, and you'll find a haven of warmth, loyalty, and steadfastness. Born between April 20th and May 20th, Taurus individuals possess an unwavering commitment to their loved ones and the values they hold dear. Grounded like the earth element that defines them, Taureans radiate a soothing, dependable presence that draws others in like a cozy fireplace on a winter's night.`
		document.querySelector('#p2').innerHTML = `With an innate appreciation for life's simple pleasures, Taurus souls revel in the beauty of nature, savoring the taste of exquisite food, and embracing the joy of meaningful relationships. Their practical sensibilities are complemented by an artistic flair, often expressed through a love for music, art, and all things aesthetically pleasing.`
		document.querySelector('#p3').innerHTML = `In the company of a Taurus, you'll experience their generosity, as they spare no effort in ensuring your comfort and happiness. They're the unwavering pillars of support during life's storms and the ones who celebrate your triumphs with unbridled enthusiasm.`
		document.querySelector('#p4').innerHTML = `So, if you're fortunate enough to have a Taurus in your life, hold onto them tightly, for they are the embodiment of a warm, loyal, and loving presence that can make every day feel like a cozy, sunlit afternoon.`
		document.querySelector('#result').style.color = 'rgb(0, 123, 0)'
		document.querySelector('#p5').innerHTML = '𓃓'
	} else if (month == 05 && date >= 21 || month == 06 && date <= 21) {
		result = ('Gemini')
		document.querySelector('#result').innerHTML = 'Gemini'
		document.querySelector('#result').style.color = 'rgb(176,223,229)'
		document.querySelector('#p1').innerHTML = `Gemini individuals is their remarkable adaptability and versatility. Geminis are known for their ability to effortlessly switch between different roles, interests, and social groups. This adaptability is often likened to having multiple personalities, but it's more about their chameleon-like ability to adjust to various situations and interact with diverse people.`
		document.querySelector('#p2').innerHTML = `Geminis are highly curious and intellectually agile, which contributes to their versatility. They have a natural thirst for knowledge and a quick wit that allows them to engage in conversations on a wide range of topics. This adaptability and versatility make Geminis excellent communicators and great at networking, as they can easily connect with people from all walks of life. They are often the life of the party, as they can effortlessly shift their social style to match the vibe of any gathering.`
		document.querySelector('#p3').innerHTML = `Another unique trait of Geminis is their dual nature, symbolized by the Twins in their zodiac sign. This duality can manifest in various ways, including having contrasting interests, personalities, or moods. Geminis can be both serious and playful, introverted and extroverted, and logical and creative, often switching between these traits based on the situation and their mood. This dual nature contributes to their complexity and makes them intriguing and multifaceted individuals.`
		document.querySelector('#p4').innerHTML = `In romantic relationships, Geminis are charming and versatile partners who bring excitement and intellectual stimulation to their connections. They are excellent communicators and enjoy engaging in lively conversations with their partners, keeping the relationship intellectually stimulating. However, their dual nature can sometimes make them appear inconsistent in their emotions, so their partners should be prepared for occasional mood swings. In platonic relationships, Geminis are fun-loving and adaptable friends who thrive in diverse social circles. They are the social butterflies of their group, able to connect with people from all walks of life due to their natural curiosity and quick wit. Geminis are loyal and supportive friends, always up for an adventure or a deep conversation, making them enjoyable companions in both lighthearted and serious moments.`
		document.querySelector('#p5').innerHTML = '𓅔'
	} else if (month == 06 && date >= 22 || month == 07 && date <= 22) {
		result = ('Cancer')
		document.querySelector('#result').innerHTML = 'Cancer'
		document.querySelector('#result').style.color = 'rgb(0,128,255)'
		document.querySelector('#p1').innerHTML = `One unique aspect of Cancer individuals is their strong emotional intelligence and empathetic nature. Cancers are highly attuned to the feelings and needs of those around them, and they often excel at providing emotional support and understanding. They have an innate ability to connect with others on a deep emotional level, making them excellent listeners and compassionate friends and partners.`
		document.querySelector('#p2').innerHTML = `Cancers are also known for their strong attachment to home and family. They have a deep sense of nostalgia and often cherish traditions and memories associated with their upbringing. This attachment to home can manifest as a strong desire to create a warm and nurturing environment for themselves and their loved ones. Cancers are often the caregivers and nurturers in their social circles, offering a safe and comforting presence to those in need.`
		document.querySelector('#p3').innerHTML = `Additionally, Cancers are ruled by the Moon, which means their emotions can ebb and flow like the tides. They may experience mood swings and deep emotional currents, but their unique ability to navigate these emotional waters gives them resilience and the capacity to offer profound emotional support to others. This combination of empathy, domesticity, and emotional depth sets Cancers apart as compassionate and loving individuals.`
		document.querySelector('#p4').innerHTML = `Cancer individuals are deeply emotional and nurturing partners in romantic relationships. They value emotional intimacy and are highly committed to their loved ones. Just as they are in romantic relationships, Cancers are nurturing friends. They remember birthdays, offer comforting advice, and are always there to lend a helping hand. Cancers love hosting gatherings at their homes, where they can create a warm and welcoming atmosphere for their friends. They enjoy cooking and creating a cozy environment for socializing.`
		document.querySelector('#p5').innerHTML = `𓋋`
	} else if (month == 07 && date >= 23 || month == 08 && date <= 22) {
		result = ('Leo')
		document.querySelector('#result').innerHTML = 'Leo'
		document.querySelector('#result').style.color = 'rgb(194,24,7)'
		document.querySelector('#p1').innerHTML = `Leos are known for their magnetic presence that lights up any room they enter. With their innate charm and self-confidence, they have a natural ability to capture the attention and admiration of those around them. Leos often find themselves in leadership roles, not only because of their authoritative demeanor but also because people are naturally drawn to their charismatic and regal aura. They thrive in social situations, effortlessly taking center stage and leaving a lasting impression with their larger-than-life personalities.`
		document.querySelector('#p2').innerHTML = `Beneath their royal exterior, Leos possess generous hearts and a strong desire to make others feel cherished and appreciated. They enjoy pampering their loved ones with acts of kindness, thoughtful gestures, and lavish gifts. Leos create a warm and welcoming atmosphere wherever they go, and their friends and family often feel like they're basking in the glow of their love and affection. Their generous nature is a testament to their caring and nurturing qualities.`
		document.querySelector('#p3').innerHTML = `Leos have a fiery creativity that fuels their artistic talents and ambitions. They excel in various creative pursuits, from acting and music to painting and writing. Their enthusiasm for self-expression is infectious, and they have a knack for infusing drama and excitement into their artistic endeavors. Leos are often at their best when they have a stage to shine on, where their creative fire burns the brightest.`
		document.querySelector('#p4').innerHTML = `Loyalty runs deep in the heart of a Leo. They are fiercely devoted to their friends and loved ones and will go to great lengths to protect and support them. Leos are like a protective shield, standing guard over the people they care about. When their loved ones face challenges or adversity, Leos are there to provide unwavering support and encouragement. Their loyalty and protective instincts make them reliable allies in both good times and bad.`
		document.querySelector('#p5').innerHTML = '𓄂'
	} else if (month == 08 && date >= 23 || month == 09 && date <= 22) {
		result = ('Virgo')
		document.querySelector('#result').innerHTML = 'Virgo'
		document.querySelector('#result').style.color = 'rgb(11,102,35)'
		document.querySelector('#p1').innerHTML = `One unique aspect of Virgo individuals is their exceptional attention to detail and their keen observational skills. Virgos have an innate ability to notice things that others might overlook, and they often excel in tasks that require precision and thoroughness. This attention to detail is not limited to work or specific projects; it extends to their daily lives, where they might notice the smallest imperfections or patterns that others might miss. As a result, Virgos tend to be highly organized and efficient individuals, making them great problem solvers and troubleshooters.`
		document.querySelector('#p2').innerHTML = `Virgos' meticulous nature also extends to their caring and nurturing qualities. They have a strong desire to help and support others, and their attention to detail allows them to anticipate the needs of those they care about. This makes them excellent caregivers and friends who can be relied upon in times of need. Their unique combination of analytical skills and a caring disposition sets them apart and makes them valuable members of their social and professional circles.`
		document.querySelector('#p3').innerHTML = `Despite their analytical and practical nature, Virgos are generally humble and unassuming. They don't seek the spotlight or recognition for their contributions but are content with knowing they've made a positive impact. Their humility endears them to others and makes them approachable and easy to work with.`
		document.querySelector('#p4').innerHTML = `Virgo individuals approach love with a thoughtful and practical mindset. They are known for their attention to detail, loyalty, and desire for a strong, stable, and meaningful relationship. In summary, Virgos approach love with a blend of practicality, loyalty, and a strong desire to create stable and meaningful relationships. They are thoughtful and considerate partners who prioritize the well-being and happiness of their loved ones. `
		document.querySelector('#p5').innerHTML = `𓁘`
	} else if (month == 09 && date >= 23 || month == 10 && date <= 23) {
		result = ('Libra')
		document.querySelector('#result').innerHTML = 'Libra'
		document.querySelector('#result').style.color = 'rgb(255,253,208)'
		document.querySelector('#p1').innerHTML = `One unique aspect of Libra individuals is their strong sense of fairness and desire for balance in all aspects of life. Libras are symbolized by the Scales, representing their deep-rooted need for equilibrium and harmony. Libras have a natural inclination toward fairness and justice. They are deeply committed to the principle of treating others with equality and impartiality. They have an innate sense of right and wrong and are often advocates for fairness, both in their personal relationships and in the wider world.`
		document.querySelector('#p2').innerHTML = `Libras tend to avoid confrontations and conflicts whenever possible. They have a strong aversion to discord and prefer to maintain peace and harmony in their interactions with others. They are skilled at diplomacy and mediation, often acting as peacemakers in their social circles.`
		document.querySelector('#p3').innerHTML = `While Libras strive for balance, their quest for fairness can sometimes lead to indecisiveness. They may weigh options meticulously, which can make it challenging for them to make decisions. However, once they make up their minds, they are committed and steadfast in their choices.`
		document.querySelector('#p4').innerHTML = `In summary, Libras' unique focus on fairness, balance, and harmony sets them apart. They are driven by a deep desire to create and maintain equilibrium in their relationships and the world around them. Their natural charm, diplomatic skills, and appreciation for aesthetics make them pleasant and engaging individuals in both personal and professional settings.`
		document.querySelector('#p5').innerHTML = `𓍝`
	} else if (month == 10 && date >= 24 || month == 11 && date <= 21) {
		result = ('Scorpio')
		document.querySelector('#result').innerHTML = 'Scorpio'
		document.querySelector('#result').style.color = 'rgb(16,52,166)'
		document.querySelector('#p1').innerHTML = `Scorpios are known for their intense and passionate nature. They approach life with a fervor that is unmatched, whether it's in their personal relationships, career pursuits, or creative endeavors. Emotions run deep within them, and they are unafraid to express their feelings with unwavering intensity. This passion is often reflected in their romantic relationships, where Scorpios seek deep, meaningful connections characterized by emotional depth and sensuality. Their passionate approach to life makes them magnetic and alluring to those around them.`
		document.querySelector('#p2').innerHTML = `Scorpios exude an air of magnetism and mystery that draws people into their orbit. They have a natural allure that captivates others, and their mysterious aura often leaves people curious to uncover the secrets and complexities within them. Scorpios tend to keep their true selves guarded, revealing layers of their personality over time, making the process of getting to know them both intriguing and rewarding.`
		document.querySelector('#p3').innerHTML = `One of the most remarkable qualities of Scorpios is their resilience. They possess the ability to endure and overcome adversity, emerging from challenges stronger and wiser. Like the mythical Phoenix, Scorpios are known for their capacity to rise from the ashes, reinventing themselves and embracing transformation. They actively seek personal growth and aren't afraid to confront their own vulnerabilities, making them individuals who are constantly evolving and seeking deeper understanding.`
		document.querySelector('#p4').innerHTML = `Scorpios have an astute and perceptive nature that sets them apart. They possess a sharp sense of intuition and can often discern underlying motives and hidden truths in various situations. This keen perception, combined with their determination and tenacity, makes them formidable individuals who can navigate complex challenges with a clear understanding of the dynamics at play. Scorpios' determination drives them to pursue their goals relentlessly, undeterred by obstacles, and they are often unyielding in their pursuit of success.`
		document.querySelector('#p5').innerHTML = `𓆫`
	} else if (month == 11 && date >= 22 || month == 12 && date <= 21) {
		result = ('Sagittarius')
		document.querySelector('#result').innerHTML = 'Sagittarius'
		document.querySelector('#result').style.color = 'rgb(124,10,2)'
		document.querySelector('#p1').innerHTML = `Sagittarians are renowned for their wanderlust and adventurous nature. They have an insatiable curiosity about the world and an intense desire to explore new places, cultures, and experiences. Travel often plays a significant role in their lives, as they seek to expand their horizons and embark on exciting adventures. Sagittarians are natural explorers, always eager to venture into the unknown, whether it's through physical travel or intellectual pursuits. Their adventurous spirit leads them to embrace life's challenges with enthusiasm and an open heart.`
		document.querySelector('#p2').innerHTML = `Sagittarians are eternal optimists who radiate positive energy wherever they go. They have an infectious enthusiasm for life that uplifts those around them. Even in the face of adversity, they maintain a hopeful outlook and a belief in the goodness of the world. Sagittarians are the friends who can infuse a sense of joy and laughter into any situation, making them enjoyable companions and reliable sources of support during tough times.`
		document.querySelector('#p3').innerHTML = `Sagittarians possess a deep intellectual curiosity and a philosophical bent of mind. They are often drawn to exploring profound questions about life, morality, and the meaning of existence. Their thirst for knowledge leads them to engage in intellectual discussions and philosophical debates, and they have a natural gift for seeing the bigger picture. Sagittarians are open-minded and willing to challenge conventional wisdom, making them free thinkers who are constantly seeking to expand their intellectual horizons.`
		document.querySelector('#p4').innerHTML = `Freedom is of paramount importance to Sagittarians. They value their independence and resist anything that feels confining or restrictive. They thrive in environments that allow them the freedom to explore, learn, and grow at their own pace. Sagittarians are not afraid to take risks or break away from the norm to pursue their dreams and follow their own unique path in life. This independent streak makes them individuals who are unapologetically true to themselves and their values, often inspiring others to do the same.`
		document.querySelector('#p5').innerHTML = `𓌕`
	} else if (month == 12 && date >= 22 || month == 01 && date <= 19) {
		result = ('Capricorn')
		document.querySelector('#result').innerHTML = 'Capricorn'
		document.querySelector('#result').style.color = 'rgb(75,83,32)'
		document.querySelector('#p1').innerHTML = `Capricorns are renowned for their strong ambition and unwavering drive to achieve their goals. They are the determined go-getters of the zodiac who work diligently to climb the ladder of success. Capricorns are not content with mediocrity; they strive for excellence in their careers, personal endeavors, and life as a whole. Their disciplined and persevering nature helps them overcome obstacles and steadily progress toward their objectives.`
		document.querySelector('#p2').innerHTML = `Capricorns have a pragmatic and responsible approach to life. They are adept at managing their resources, making sensible decisions, and planning for the future. Capricorns often take on leadership roles and are trusted for their practical wisdom. They value stability and security, and their strong work ethic ensures that they meet their responsibilities and commitments with utmost diligence.`
		document.querySelector('#p3').innerHTML = `Capricorns tend to be reserved and composed individuals who approach situations with patience and caution. They rarely rush into decisions and prefer to take their time, carefully considering their options. This patient demeanor allows them to make well-thought-out choices and withstand challenges with a calm and collected attitude. Capricorns are often the voice of reason in tumultuous situations.`
		document.querySelector('#p4').innerHTML = `Capricorns hold traditional values, including a strong sense of duty, loyalty, and integrity. They are steadfast and loyal friends, family members, and partners. Once they commit to a relationship or a cause, they do so with unwavering dedication. Capricorns are dependable and can be counted on to support and protect their loved ones, making them valued confidants and allies.`
		document.querySelector('#p5').innerHTML = `𓃛`
	} else if (month == 01 && date >= 20 || month == 02 && date <= 18) {
		result = ('Aquarius')
		document.querySelector('#result').innerHTML = 'Aquarius'
		document.querySelector('#result').style.color = 'rgb(169,186,157)'
		document.querySelector('#p1').innerHTML = `Aquarians are often heralded as some of the most innovative and forward-thinking individuals in the zodiac. They possess a natural inclination toward unconventional ideas, groundbreaking concepts, and visionary thinking. Aquarians are drawn to technology, science, and progressive movements, and they excel at envisioning a future that challenges the status quo. Their inventive and open-minded approach to life makes them pioneers in various fields and valuable contributors to the advancement of society.`
		document.querySelector('#p2').innerHTML = `Aquarians have a deep sense of social responsibility and a genuine concern for the well-being of humanity. They are often involved in social causes, activism, and charitable endeavors. Their humanitarian spirit drives them to make a positive impact on the world, whether through advocating for social justice, championing environmental causes, or supporting the underprivileged. Aquarians are passionate about creating a more equitable and compassionate society.`
		document.querySelector('#p3').innerHTML = `Independence is highly prized by Aquarians, and they are natural nonconformists. They resist being pigeonholed into societal norms or expectations and often march to the beat of their own drum. Aquarians are unapologetically authentic, valuing their individuality and freedom of thought. Their nonconformity extends to their fashion choices, lifestyles, and unique perspectives on life, making them stand out as trailblazers and trendsetters.`
		document.querySelector('#p4').innerHTML = `Aquarians are renowned for their intellectual prowess and eccentric personalities. They have a thirst for knowledge and an insatiable curiosity about the world. Their minds are agile and inventive, allowing them to come up with ingenious solutions to complex problems. Aquarians are often attracted to unconventional hobbies, interests, and art forms, and they appreciate the unusual and quirky aspects of life. Their eccentricity is celebrated as a source of inspiration and creativity.`
		document.querySelector('#p5').innerHTML = `𓈗`
	} else if (month == 02 && date >= 19 || month == 03 && date <= 20) {
		result = ('Pisces')
		document.querySelector('#result').innerHTML = 'Pisces'
		document.querySelector('#result').style.color = 'rgb(0,0,128)'
		document.querySelector('#p1').innerHTML = `Pisces are renowned for their deep empathy and compassion. They have an innate ability to connect with the emotions of others, often experiencing the feelings of those around them as if they were their own. This makes them highly sensitive and caring individuals who are quick to offer support and comfort to those in need. Pisces are often seen as natural healers and empathetic listeners, making them trustworthy and empathetic friends and partners.`
		document.querySelector('#p2').innerHTML = `Pisces individuals possess a vivid and imaginative inner world. They have a strong creative streak and often excel in artistic pursuits, such as music, visual arts, writing, or dance. Their imagination knows no bounds, and they are adept at finding inspiration in the ethereal and dreamlike realms. Pisces often have a unique ability to express their emotions and ideas through their chosen creative outlets.`
		document.querySelector('#p3').innerHTML = `Pisces are remarkably adaptable and flexible individuals. They have a go-with-the-flow attitude that allows them to navigate life's twists and turns with relative ease. They can adjust to changing circumstances and are often open to new experiences and ideas. Pisces' adaptability makes them comfortable in a wide range of social settings and situations, as they have a natural ability to blend in and connect with diverse groups of people.`
		document.querySelector('#p4').innerHTML = `Pisces have a strong intuitive and spiritual side. They often have a deep interest in mystical and spiritual matters, such as astrology, meditation, or metaphysics. Their intuition is finely tuned, and they often trust their inner guidance when making decisions. Pisces may have a penchant for exploring the mysteries of the universe and seeking a deeper connection with the spiritual or metaphysical aspects of life.`
		document.querySelector('#p5').innerHTML = `𓆟`
	} else (
		document.querySelector('#result').innerHTML = 'Try again with a valid date'
	)
}




// ♈ Aries (Ram): March 21–April 19
// ♉ Taurus (Bull): April 20–May 20
// ♊ Gemini (Twins): May 21–June 21
// ♋ Cancer (Crab): June 22–July 22
// ♌ Leo (Lion): July 23–August 22
// ♍ Virgo (Virgin): August 23–September 22
// ♎ Libra (Balance): September 23–October 23
// ♏ Scorpius (Scorpion): October 24–November 21
// ♐ Sagittarius (Archer): November 22–December 21
// ♑ Capricornus (Goat): December 22–January 19
// ♒ Aquarius (Water Bearer): January 20–February 18
// ♓ Pisces (Fish): February 19–March 20